flowchart TD
    A[Carregamento: DoS.csv] --> B[Limpeza e Tratamento]
    B --> C[Split Train/Test e Scaler]
    
    subgraph Fase 1: Baseline e Seleção
        C --> D[Treinar 6 Modelos Baseline]
        C --> E[7 Seletores de Feature]
        E --> F[Features de Consenso]
    end

    subgraph Fase 2: Optuna
        F --> H[Optuna Global\nCria os 6 Modelos 'Elite']
        E --> I[Optuna por Seletor]
    end
    
    subgraph Fase 3: Super Ensemble
        H -. Fornece os 6 modelos otimizados .-> J[Ensemble com Modelos Otimizados]
        
        J --> K[1. Averaging\nMédia simples]
        J --> L[2. Hard Voting\nVoto por maioria simples]
        J --> M[3. Smart Soft Voting\nOptuna acha os pesos ideais]
    end
    
    classDef green fill:#ccffcc,stroke:#00aa00,stroke-width:2px;
    class Fase3,J,K,L,M green;
